name: Adam Rasheed
description: Front-end Developer

seo_desc: Adam Rasheed is a front-end developer based in Southern California who loves working in Wordpress, Shopify and React. He also loves doing UI/UX design in Sketch in Figma. Need some help on your next project? Let‘s talk!
image: /assets/Adam-Rasheed-Pano-web@2x.jpg
tagline: I’m a Front-end Developer based in Southern California.

email: adamrasheed91@gmail.com
resume: https://www.dropbox.com/s/55xlzhq0tq63bn8/Adam-Rasheed-CV-Dev-2017.pdf?dl=0

url: https://adamrasheed.com


markdown: kramdown
highlighter: rouge # or rouge or null
include: ['case-studies']
exclude: ["node_modules", "gulpfile.js", "package.json"]
permalink: /:title/
